### ISSUE TITLE
dl2c = tf.stop_gradient(dl2c) - Failed to convert object of type <class 'list'> to Tensor

### ISSUE THREAD

**Issue by ebalda** [nilboy/colorization-tf#4]
`Traceback (most recent call last):`
`File "tools/train.py", line 23, in <module>`
`    solver.train_model()`
`  File "./solver.py", line 57, in train_model`
`    new_loss, self.total_loss = self.construct_graph(scope)`
`  File "./solver.py", line 45, in construct_graph`
`    new_loss, g_loss = self.net.loss(scope, self.conv8_313, self.prior_boost_nongray, self.gt_ab_313)`
`  File "./net.py", line 132, in loss`
`    dl2c = tf.stop_gradient(dl2c)`
`  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 5220, in stop_gradient`
`    "StopGradient", input=input, name=name)`
.
.
.
`TypeError: Failed to convert object of type <class 'list'> to Tensor. Contents: [None]. Consider casting elements to a supported type.`

_PS: It seems to me that this script was made using Python 2.7, which tensforflow version do you use?
Could I ask for the dependencies?_

**Comment by govindvs** [comment]
It will be very helpful if you could comment or suggest another workaround.

I am using python 2.7. I am also experiencing the same trouble. what factor are u trying to extract with that step . where is it described. your input will be very helpful
